"""empty message

Revision ID: c1f08135f9bf
Revises: 
Create Date: 2019-03-05 08:34:41.407497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f08135f9bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('hname', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'roles', ['hname'])
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'hname')
    # ### end Alembic commands ###
