"""empty message

Revision ID: c9bb2b1d659c
Revises: c1f08135f9bf
Create Date: 2019-03-05 08:35:23.783181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9bb2b1d659c'
down_revision = 'c1f08135f9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('hname', table_name='roles')
    op.drop_column('roles', 'hname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('hname', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('hname', 'roles', ['hname'], unique=True)
    # ### end Alembic commands ###
